using System;

namespace theori.IO
{
    public class KeyInfo
    {
        public ScanCode ScanCode;
        public KeyCode KeyCode;
        public KeyMod Mods;
    }

	public enum ScanCode
	{
		UNKNOWN = 0,

		A = 4,
		B = 5,
		C = 6,
		D = 7,
		E = 8,
		F = 9,
		G = 10,
		H = 11,
		I = 12,
		J = 13,
		K = 14,
		L = 15,
		M = 16,
		N = 17,
		O = 18,
		P = 19,
		Q = 20,
		R = 21,
		S = 22,
		T = 23,
		U = 24,
		V = 25,
		W = 26,
		X = 27,
		Y = 28,
		Z = 29,

		D1 = 30,
		D2 = 31,
		D3 = 32,
		D4 = 33,
		D5 = 34,
		D6 = 35,
		D7 = 36,
		D8 = 37,
		D9 = 38,
		D0 = 39,

		RETURN = 40,
		ESCAPE = 41,
		BACKSPACE = 42,
		TAB = 43,
		SPACE = 44,

		MINUS = 45,
		EQUALS = 46,
		LEFTBRACKET = 47,
		RIGHTBRACKET = 48,
		BACKSLASH = 49,
		NONUSHASH = 50,
		SEMICOLON = 51,
		APOSTROPHE = 52,
		GRAVE = 53,
		COMMA = 54,
		PERIOD = 55,
		SLASH = 56,

		CAPSLOCK = 57,

		F1 = 58,
		F2 = 59,
		F3 = 60,
		F4 = 61,
		F5 = 62,
		F6 = 63,
		F7 = 64,
		F8 = 65,
		F9 = 66,
		F10 = 67,
		F11 = 68,
		F12 = 69,

		PRINTSCREEN = 70,
		SCROLLLOCK = 71,
		PAUSE = 72,
		INSERT = 73,
		HOME = 74,
		PAGEUP = 75,
		DELETE = 76,
		END = 77,
		PAGEDOWN = 78,
		RIGHT = 79,
		LEFT = 80,
		DOWN = 81,
		UP = 82,

		NUMLOCKCLEAR = 83,
		KP_DIVIDE = 84,
		KP_MULTIPLY = 85,
		KP_MINUS = 86,
		KP_PLUS = 87,
		KP_ENTER = 88,
		KP_1 = 89,
		KP_2 = 90,
		KP_3 = 91,
		KP_4 = 92,
		KP_5 = 93,
		KP_6 = 94,
		KP_7 = 95,
		KP_8 = 96,
		KP_9 = 97,
		KP_0 = 98,
		KP_PERIOD = 99,

		NONUSBACKSLASH = 100,
		APPLICATION = 101,
		POWER = 102,
		KP_EQUALS = 103,
		F13 = 104,
		F14 = 105,
		F15 = 106,
		F16 = 107,
		F17 = 108,
		F18 = 109,
		F19 = 110,
		F20 = 111,
		F21 = 112,
		F22 = 113,
		F23 = 114,
		F24 = 115,
		EXECUTE = 116,
		HELP = 117,
		MENU = 118,
		SELECT = 119,
		STOP = 120,
		AGAIN = 121,
		UNDO = 122,
		CUT = 123,
		COPY = 124,
		PASTE = 125,
		FIND = 126,
		MUTE = 127,
		VOLUMEUP = 128,
		VOLUMEDOWN = 129,
		/* not sure whether there's a reason to enable these */
		/*	LOCKINGCAPSLOCK = 130, */
		/*	LOCKINGNUMLOCK = 131, */
		/*	LOCKINGSCROLLLOCK = 132, */
		KP_COMMA = 133,
		KP_EQUALSAS400 = 134,

		INTERNATIONAL1 = 135,
		INTERNATIONAL2 = 136,
		INTERNATIONAL3 = 137,
		INTERNATIONAL4 = 138,
		INTERNATIONAL5 = 139,
		INTERNATIONAL6 = 140,
		INTERNATIONAL7 = 141,
		INTERNATIONAL8 = 142,
		INTERNATIONAL9 = 143,
		LANG1 = 144,
		LANG2 = 145,
		LANG3 = 146,
		LANG4 = 147,
		LANG5 = 148,
		LANG6 = 149,
		LANG7 = 150,
		LANG8 = 151,
		LANG9 = 152,

		ALTERASE = 153,
		SYSREQ = 154,
		CANCEL = 155,
		CLEAR = 156,
		PRIOR = 157,
		RETURN2 = 158,
		SEPARATOR = 159,
		OUT = 160,
		OPER = 161,
		CLEARAGAIN = 162,
		CRSEL = 163,
		EXSEL = 164,

		KP_00 = 176,
		KP_000 = 177,
		THOUSANDSSEPARATOR = 178,
		DECIMALSEPARATOR = 179,
		CURRENCYUNIT = 180,
		CURRENCYSUBUNIT = 181,
		KP_LEFTPAREN = 182,
		KP_RIGHTPAREN = 183,
		KP_LEFTBRACE = 184,
		KP_RIGHTBRACE = 185,
		KP_TAB = 186,
		KP_BACKSPACE = 187,
		KP_A = 188,
		KP_B = 189,
		KP_C = 190,
		KP_D = 191,
		KP_E = 192,
		KP_F = 193,
		KP_XOR = 194,
		KP_POWER = 195,
		KP_PERCENT = 196,
		KP_LESS = 197,
		KP_GREATER = 198,
		KP_AMPERSAND = 199,
		KP_DBLAMPERSAND = 200,
		KP_VERTICALBAR = 201,
		KP_DBLVERTICALBAR = 202,
		KP_COLON = 203,
		KP_HASH = 204,
		KP_SPACE = 205,
		KP_AT = 206,
		KP_EXCLAM = 207,
		KP_MEMSTORE = 208,
		KP_MEMRECALL = 209,
		KP_MEMCLEAR = 210,
		KP_MEMADD = 211,
		KP_MEMSUBTRACT = 212,
		KP_MEMMULTIPLY = 213,
		KP_MEMDIVIDE = 214,
		KP_PLUSMINUS = 215,
		KP_CLEAR = 216,
		KP_CLEARENTRY = 217,
		KP_BINARY = 218,
		KP_OCTAL = 219,
		KP_DECIMAL = 220,
		KP_HEXADECIMAL = 221,

		LCTRL = 224,
		LSHIFT = 225,
		LALT = 226,
		LGUI = 227,
		RCTRL = 228,
		RSHIFT = 229,
		RALT = 230,
		RGUI = 231,

		MODE = 257,

		/* These come from the USB consumer page (0x0C) */
		AUDIONEXT = 258,
		AUDIOPREV = 259,
		AUDIOSTOP = 260,
		AUDIOPLAY = 261,
		AUDIOMUTE = 262,
		MEDIASELECT = 263,
		WWW = 264,
		MAIL = 265,
		CALCULATOR = 266,
		COMPUTER = 267,
		AC_SEARCH = 268,
		AC_HOME = 269,
		AC_BACK = 270,
		AC_FORWARD = 271,
		AC_STOP = 272,
		AC_REFRESH = 273,
		AC_BOOKMARKS = 274,

		/* These come from other sources, and are mostly mac related */
		BRIGHTNESSDOWN = 275,
		BRIGHTNESSUP = 276,
		DISPLAYSWITCH = 277,
		KBDILLUMTOGGLE = 278,
		KBDILLUMDOWN = 279,
		KBDILLUMUP = 280,
		EJECT = 281,
		SLEEP = 282,

		APP1 = 283,
		APP2 = 284,

		/* This is not a key, simply marks the number of scancodes
			* so that you know how big to make your arrays. */
		NUM_SCANCODES = 512
	}
    
	public enum KeyCode
	{
		UNKNOWN = 0,

		RETURN = '\r',
		ESCAPE = 27, // '\033'
		BACKSPACE = '\b',
		TAB = '\t',
		SPACE = ' ',
		EXCLAIM = '!',
		QUOTEDBL = '"',
		HASH = '#',
		PERCENT = '%',
		DOLLAR = '$',
		AMPERSAND = '&',
		QUOTE = '\'',
		LEFTPAREN = '(',
		RIGHTPAREN = ')',
		ASTERISK = '*',
		PLUS = '+',
		COMMA = ',',
		MINUS = '-',
		PERIOD = '.',
		SLASH = '/',
		D0 = '0',
		D1 = '1',
		D2 = '2',
		D3 = '3',
		D4 = '4',
		D5 = '5',
		D6 = '6',
		D7 = '7',
		D8 = '8',
		D9 = '9',
		COLON = ':',
		SEMICOLON = ';',
		LESS = '<',
		EQUALS = '=',
		GREATER = '>',
		QUESTION = '?',
		AT = '@',
		/*
		Skip uppercase letters
		*/
		LEFTBRACKET = '[',
		BACKSLASH = '\\',
		RIGHTBRACKET = ']',
		CARET = '^',
		UNDERSCORE = '_',
		BACKQUOTE = '`',
		A = 'a',
		B = 'b',
		C = 'c',
		D = 'd',
		E = 'e',
		F = 'f',
		G = 'g',
		H = 'h',
		I = 'i',
		J = 'j',
		K = 'k',
		L = 'l',
		M = 'm',
		N = 'n',
		O = 'o',
		P = 'p',
		Q = 'q',
		R = 'r',
		S = 's',
		T = 't',
		U = 'u',
		V = 'v',
		W = 'w',
		X = 'x',
		Y = 'y',
		Z = 'z',

		CAPSLOCK = ScanCode.CAPSLOCK | Keyboard.SCANCODE_MASK,

		F1 = ScanCode.F1 | Keyboard.SCANCODE_MASK,
		F2 = ScanCode.F2 | Keyboard.SCANCODE_MASK,
		F3 = ScanCode.F3 | Keyboard.SCANCODE_MASK,
		F4 = ScanCode.F4 | Keyboard.SCANCODE_MASK,
		F5 = ScanCode.F5 | Keyboard.SCANCODE_MASK,
		F6 = ScanCode.F6 | Keyboard.SCANCODE_MASK,
		F7 = ScanCode.F7 | Keyboard.SCANCODE_MASK,
		F8 = ScanCode.F8 | Keyboard.SCANCODE_MASK,
		F9 = ScanCode.F9 | Keyboard.SCANCODE_MASK,
		F10 = ScanCode.F10 | Keyboard.SCANCODE_MASK,
		F11 = ScanCode.F11 | Keyboard.SCANCODE_MASK,
		F12 = ScanCode.F12 | Keyboard.SCANCODE_MASK,

		PRINTSCREEN = ScanCode.PRINTSCREEN | Keyboard.SCANCODE_MASK,
		SCROLLLOCK = ScanCode.SCROLLLOCK | Keyboard.SCANCODE_MASK,
		PAUSE = ScanCode.PAUSE | Keyboard.SCANCODE_MASK,
		INSERT = ScanCode.INSERT | Keyboard.SCANCODE_MASK,
		HOME = ScanCode.HOME | Keyboard.SCANCODE_MASK,
		PAGEUP = ScanCode.PAGEUP | Keyboard.SCANCODE_MASK,
		DELETE = 127,
		END = ScanCode.END | Keyboard.SCANCODE_MASK,
		PAGEDOWN = ScanCode.PAGEDOWN | Keyboard.SCANCODE_MASK,
		RIGHT = ScanCode.RIGHT | Keyboard.SCANCODE_MASK,
		LEFT = ScanCode.LEFT | Keyboard.SCANCODE_MASK,
		DOWN = ScanCode.DOWN | Keyboard.SCANCODE_MASK,
		UP = ScanCode.UP | Keyboard.SCANCODE_MASK,

		NUMLOCKCLEAR = ScanCode.NUMLOCKCLEAR | Keyboard.SCANCODE_MASK,
		KP_DIVIDE = ScanCode.KP_DIVIDE | Keyboard.SCANCODE_MASK,
		KP_MULTIPLY = ScanCode.KP_MULTIPLY | Keyboard.SCANCODE_MASK,
		KP_MINUS = ScanCode.KP_MINUS | Keyboard.SCANCODE_MASK,
		KP_PLUS = ScanCode.KP_PLUS | Keyboard.SCANCODE_MASK,
		KP_ENTER = ScanCode.KP_ENTER | Keyboard.SCANCODE_MASK,
		KP_1 = ScanCode.KP_1 | Keyboard.SCANCODE_MASK,
		KP_2 = ScanCode.KP_2 | Keyboard.SCANCODE_MASK,
		KP_3 = ScanCode.KP_3 | Keyboard.SCANCODE_MASK,
		KP_4 = ScanCode.KP_4 | Keyboard.SCANCODE_MASK,
		KP_5 = ScanCode.KP_5 | Keyboard.SCANCODE_MASK,
		KP_6 = ScanCode.KP_6 | Keyboard.SCANCODE_MASK,
		KP_7 = ScanCode.KP_7 | Keyboard.SCANCODE_MASK,
		KP_8 = ScanCode.KP_8 | Keyboard.SCANCODE_MASK,
		KP_9 = ScanCode.KP_9 | Keyboard.SCANCODE_MASK,
		KP_0 = ScanCode.KP_0 | Keyboard.SCANCODE_MASK,
		KP_PERIOD = ScanCode.KP_PERIOD | Keyboard.SCANCODE_MASK,

		APPLICATION = ScanCode.APPLICATION | Keyboard.SCANCODE_MASK,
		POWER = ScanCode.POWER | Keyboard.SCANCODE_MASK,
		KP_EQUALS = ScanCode.KP_EQUALS | Keyboard.SCANCODE_MASK,
		F13 = ScanCode.F13 | Keyboard.SCANCODE_MASK,
		F14 = ScanCode.F14 | Keyboard.SCANCODE_MASK,
		F15 = ScanCode.F15 | Keyboard.SCANCODE_MASK,
		F16 = ScanCode.F16 | Keyboard.SCANCODE_MASK,
		F17 = ScanCode.F17 | Keyboard.SCANCODE_MASK,
		F18 = ScanCode.F18 | Keyboard.SCANCODE_MASK,
		F19 = ScanCode.F19 | Keyboard.SCANCODE_MASK,
		F20 = ScanCode.F20 | Keyboard.SCANCODE_MASK,
		F21 = ScanCode.F21 | Keyboard.SCANCODE_MASK,
		F22 = ScanCode.F22 | Keyboard.SCANCODE_MASK,
		F23 = ScanCode.F23 | Keyboard.SCANCODE_MASK,
		F24 = ScanCode.F24 | Keyboard.SCANCODE_MASK,
		EXECUTE = ScanCode.EXECUTE | Keyboard.SCANCODE_MASK,
		HELP = ScanCode.HELP | Keyboard.SCANCODE_MASK,
		MENU = ScanCode.MENU | Keyboard.SCANCODE_MASK,
		SELECT = ScanCode.SELECT | Keyboard.SCANCODE_MASK,
		STOP = ScanCode.STOP | Keyboard.SCANCODE_MASK,
		AGAIN = ScanCode.AGAIN | Keyboard.SCANCODE_MASK,
		UNDO = ScanCode.UNDO | Keyboard.SCANCODE_MASK,
		CUT = ScanCode.CUT | Keyboard.SCANCODE_MASK,
		COPY = ScanCode.COPY | Keyboard.SCANCODE_MASK,
		PASTE = ScanCode.PASTE | Keyboard.SCANCODE_MASK,
		FIND = ScanCode.FIND | Keyboard.SCANCODE_MASK,
		MUTE = ScanCode.MUTE | Keyboard.SCANCODE_MASK,
		VOLUMEUP = ScanCode.VOLUMEUP | Keyboard.SCANCODE_MASK,
		VOLUMEDOWN = ScanCode.VOLUMEDOWN | Keyboard.SCANCODE_MASK,
		KP_COMMA = ScanCode.KP_COMMA | Keyboard.SCANCODE_MASK,
		KP_EQUALSAS400 = ScanCode.KP_EQUALSAS400 | Keyboard.SCANCODE_MASK,

		ALTERASE = ScanCode.ALTERASE | Keyboard.SCANCODE_MASK,
		SYSREQ = ScanCode.SYSREQ | Keyboard.SCANCODE_MASK,
		CANCEL = ScanCode.CANCEL | Keyboard.SCANCODE_MASK,
		CLEAR = ScanCode.CLEAR | Keyboard.SCANCODE_MASK,
		PRIOR = ScanCode.PRIOR | Keyboard.SCANCODE_MASK,
		RETURN2 = ScanCode.RETURN2 | Keyboard.SCANCODE_MASK,
		SEPARATOR = ScanCode.SEPARATOR | Keyboard.SCANCODE_MASK,
		OUT = ScanCode.OUT | Keyboard.SCANCODE_MASK,
		OPER = ScanCode.OPER | Keyboard.SCANCODE_MASK,
		CLEARAGAIN = ScanCode.CLEARAGAIN | Keyboard.SCANCODE_MASK,
		CRSEL = ScanCode.CRSEL | Keyboard.SCANCODE_MASK,
		EXSEL = ScanCode.EXSEL | Keyboard.SCANCODE_MASK,

		KP_00 = ScanCode.KP_00 | Keyboard.SCANCODE_MASK,
		KP_000 = ScanCode.KP_000 | Keyboard.SCANCODE_MASK,
		THOUSANDSSEPARATOR = ScanCode.THOUSANDSSEPARATOR | Keyboard.SCANCODE_MASK,
		DECIMALSEPARATOR = ScanCode.DECIMALSEPARATOR | Keyboard.SCANCODE_MASK,
		CURRENCYUNIT = ScanCode.CURRENCYUNIT | Keyboard.SCANCODE_MASK,
		CURRENCYSUBUNIT = ScanCode.CURRENCYSUBUNIT | Keyboard.SCANCODE_MASK,
		KP_LEFTPAREN = ScanCode.KP_LEFTPAREN | Keyboard.SCANCODE_MASK,
		KP_RIGHTPAREN = ScanCode.KP_RIGHTPAREN | Keyboard.SCANCODE_MASK,
		KP_LEFTBRACE = ScanCode.KP_LEFTBRACE | Keyboard.SCANCODE_MASK,
		KP_RIGHTBRACE = ScanCode.KP_RIGHTBRACE | Keyboard.SCANCODE_MASK,
		KP_TAB = ScanCode.KP_TAB | Keyboard.SCANCODE_MASK,
		KP_BACKSPACE = ScanCode.KP_BACKSPACE | Keyboard.SCANCODE_MASK,
		KP_A = ScanCode.KP_A | Keyboard.SCANCODE_MASK,
		KP_B = ScanCode.KP_B | Keyboard.SCANCODE_MASK,
		KP_C = ScanCode.KP_C | Keyboard.SCANCODE_MASK,
		KP_D = ScanCode.KP_D | Keyboard.SCANCODE_MASK,
		KP_E = ScanCode.KP_E | Keyboard.SCANCODE_MASK,
		KP_F = ScanCode.KP_F | Keyboard.SCANCODE_MASK,
		KP_XOR = ScanCode.KP_XOR | Keyboard.SCANCODE_MASK,
		KP_POWER = ScanCode.KP_POWER | Keyboard.SCANCODE_MASK,
		KP_PERCENT = ScanCode.KP_PERCENT | Keyboard.SCANCODE_MASK,
		KP_LESS = ScanCode.KP_LESS | Keyboard.SCANCODE_MASK,
		KP_GREATER = ScanCode.KP_GREATER | Keyboard.SCANCODE_MASK,
		KP_AMPERSAND = ScanCode.KP_AMPERSAND | Keyboard.SCANCODE_MASK,
		KP_DBLAMPERSAND = ScanCode.KP_DBLAMPERSAND | Keyboard.SCANCODE_MASK,
		KP_VERTICALBAR = ScanCode.KP_VERTICALBAR | Keyboard.SCANCODE_MASK,
		KP_DBLVERTICALBAR = ScanCode.KP_DBLVERTICALBAR | Keyboard.SCANCODE_MASK,
		KP_COLON = ScanCode.KP_COLON | Keyboard.SCANCODE_MASK,
		KP_HASH = ScanCode.KP_HASH | Keyboard.SCANCODE_MASK,
		KP_SPACE = ScanCode.KP_SPACE | Keyboard.SCANCODE_MASK,
		KP_AT = ScanCode.KP_AT | Keyboard.SCANCODE_MASK,
		KP_EXCLAM = ScanCode.KP_EXCLAM | Keyboard.SCANCODE_MASK,
		KP_MEMSTORE = ScanCode.KP_MEMSTORE | Keyboard.SCANCODE_MASK,
		KP_MEMRECALL = ScanCode.KP_MEMRECALL | Keyboard.SCANCODE_MASK,
		KP_MEMCLEAR = ScanCode.KP_MEMCLEAR | Keyboard.SCANCODE_MASK,
		KP_MEMADD = ScanCode.KP_MEMADD | Keyboard.SCANCODE_MASK,
		KP_MEMSUBTRACT = ScanCode.KP_MEMSUBTRACT | Keyboard.SCANCODE_MASK,
		KP_MEMMULTIPLY = ScanCode.KP_MEMMULTIPLY | Keyboard.SCANCODE_MASK,
		KP_MEMDIVIDE = ScanCode.KP_MEMDIVIDE | Keyboard.SCANCODE_MASK,
		KP_PLUSMINUS = ScanCode.KP_PLUSMINUS | Keyboard.SCANCODE_MASK,
		KP_CLEAR = ScanCode.KP_CLEAR | Keyboard.SCANCODE_MASK,
		KP_CLEARENTRY = ScanCode.KP_CLEARENTRY | Keyboard.SCANCODE_MASK,
		KP_BINARY = ScanCode.KP_BINARY | Keyboard.SCANCODE_MASK,
		KP_OCTAL = ScanCode.KP_OCTAL | Keyboard.SCANCODE_MASK,
		KP_DECIMAL = ScanCode.KP_DECIMAL | Keyboard.SCANCODE_MASK,
		KP_HEXADECIMAL = ScanCode.KP_HEXADECIMAL | Keyboard.SCANCODE_MASK,

		LCTRL = ScanCode.LCTRL | Keyboard.SCANCODE_MASK,
		LSHIFT = ScanCode.LSHIFT | Keyboard.SCANCODE_MASK,
		LALT = ScanCode.LALT | Keyboard.SCANCODE_MASK,
		LGUI = ScanCode.LGUI | Keyboard.SCANCODE_MASK,
		RCTRL = ScanCode.RCTRL | Keyboard.SCANCODE_MASK,
		RSHIFT = ScanCode.RSHIFT | Keyboard.SCANCODE_MASK,
		RALT = ScanCode.RALT | Keyboard.SCANCODE_MASK,
		RGUI = ScanCode.RGUI | Keyboard.SCANCODE_MASK,

		MODE = ScanCode.MODE | Keyboard.SCANCODE_MASK,

		AUDIONEXT = ScanCode.AUDIONEXT | Keyboard.SCANCODE_MASK,
		AUDIOPREV = ScanCode.AUDIOPREV | Keyboard.SCANCODE_MASK,
		AUDIOSTOP = ScanCode.AUDIOSTOP | Keyboard.SCANCODE_MASK,
		AUDIOPLAY = ScanCode.AUDIOPLAY | Keyboard.SCANCODE_MASK,
		AUDIOMUTE = ScanCode.AUDIOMUTE | Keyboard.SCANCODE_MASK,
		MEDIASELECT = ScanCode.MEDIASELECT | Keyboard.SCANCODE_MASK,
		WWW = ScanCode.WWW | Keyboard.SCANCODE_MASK,
		MAIL = ScanCode.MAIL | Keyboard.SCANCODE_MASK,
		CALCULATOR = ScanCode.CALCULATOR | Keyboard.SCANCODE_MASK,
		COMPUTER = ScanCode.COMPUTER | Keyboard.SCANCODE_MASK,
		AC_SEARCH = ScanCode.AC_SEARCH | Keyboard.SCANCODE_MASK,
		AC_HOME = ScanCode.AC_HOME | Keyboard.SCANCODE_MASK,
		AC_BACK = ScanCode.AC_BACK | Keyboard.SCANCODE_MASK,
		AC_FORWARD = ScanCode.AC_FORWARD | Keyboard.SCANCODE_MASK,
		AC_STOP = ScanCode.AC_STOP | Keyboard.SCANCODE_MASK,
		AC_REFRESH = ScanCode.AC_REFRESH | Keyboard.SCANCODE_MASK,
		AC_BOOKMARKS = ScanCode.AC_BOOKMARKS | Keyboard.SCANCODE_MASK,

		BRIGHTNESSDOWN = ScanCode.BRIGHTNESSDOWN | Keyboard.SCANCODE_MASK,
		BRIGHTNESSUP = ScanCode.BRIGHTNESSUP | Keyboard.SCANCODE_MASK,
		DISPLAYSWITCH = ScanCode.DISPLAYSWITCH | Keyboard.SCANCODE_MASK,
		KBDILLUMTOGGLE = ScanCode.KBDILLUMTOGGLE | Keyboard.SCANCODE_MASK,
		KBDILLUMDOWN = ScanCode.KBDILLUMDOWN | Keyboard.SCANCODE_MASK,
		KBDILLUMUP = ScanCode.KBDILLUMUP | Keyboard.SCANCODE_MASK,
		EJECT = ScanCode.EJECT | Keyboard.SCANCODE_MASK,
		SLEEP = ScanCode.SLEEP | Keyboard.SCANCODE_MASK
	}

	/* Key modifiers (bitfield) */
	[Flags]
	public enum KeyMod : ushort
	{
		NONE = 0x0000,
		LSHIFT = 0x0001,
		RSHIFT = 0x0002,
		LCTRL = 0x0040,
		RCTRL = 0x0080,
		LALT = 0x0100,
		RALT = 0x0200,
		LGUI = 0x0400,
		RGUI = 0x0800,
		NUM = 0x1000,
		CAPS = 0x2000,
		MODE = 0x4000,
		RESERVED = 0x8000,

		CTRL = LCTRL | RCTRL,
		SHIFT = LSHIFT | RSHIFT,
		ALT = LALT | RALT,
		GUI = LGUI | RGUI
	}
}
